name: Build and push services

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-deploy:
    continue-on-error: true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: 
          - folder: backend
            name: backend
          - folder: frontend
            name: frontend
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          #cache-from: "racembenrhayem/${{ matrix.service.name }}:latest"
          file: ${ {matrix.service.folder }}/Dockerfile
          context: "{{defaultContext}}:backend"
          push: true
          tags: |
            racembenrhayem/${{ matrix.service.name }}:latest
            racembenrhayem/${{ matrix.service.name }}:${{ github.sha }}
